### PR TITLE
Use ClassTransformer-based method of patching for tickrate

### PR DESCRIPTION
**Pull request by zhuyifei1999**
Now with Forge compatibility.

This is probably a stretch, but I'm happy to answer any questions regarding the patch or discuss other options.

### CODE REVIEW

**Comment by X-com** [comment]
This feature never worked and the solution proposed makes it unholy worse to debug. Unless the feature now works after the changes then its worth implementing. Unless it does help fix it then its best to rip it out or fix it before adding transformers that I'm completely unfamiliar with making that much more harder to debug.

**Comment by zhuyifei1999** [comment]
Works for me. The decompiled code (from runtime decompilation with `gradlew runClient`) make sense to me as well. It looks like:

```java
    public void runTick() throws IOException {
        this.handler$fixingPistons$zbf000(new CallbackInfo("runTick", false));
        this.handler$tickPlayer$zbf000(new CallbackInfo("runTick", false));
        this.handler$newTick$zcj000(new CallbackInfo("runTick", false));
        int tickWorld = false;
        if (this.timer.elapsedTicksWorld > 0) {
            --this.timer.elapsedTicksWorld;
            tickWorld = true;
        }

        int tickPlayer = false;
        if (this.timer.elapsedTicksPlayer > 0) {
            --this.timer.elapsedTicksPlayer;
            tickPlayer = true;
        }

        if (this.[...] > 0 && tickPlayer) {
            --this.[...];
        }

        this.[...]
        if (!this.[...] && tickPlayer) {
            this.[...]
        }
[...]
```

(redacted not-so-relevant names of game methods and fields because of MCP license...)

The only discomfort for me is that the player movement speed is affected by world tick rate instead of player, which I guess is probably way too complicated to fix. I tried changing the tickrate for EntityPlayerSP to player rate at https://github.com/zhuyifei1999/CarpetClient/commit/6907350dd56c3b4cf1fd5aa60f722a4e790a2e35, caused the player to be moving at different velocities between rendering / ticking, causing major rendering glitches.

**Comment by X-com** [comment]
Can we merge this into an experimental branch to do tests on before merging into main branch. I still have high doubts about this feature being fixed given it was extremely broken and still might be. It needs more testing before its reliably confirmed working.

**Comment by zhuyifei1999** [comment]
Sure, I don't mind where it's merged to. Just proposing a possible solution. ;)

Shall I do a PR or are you doing a merge to a new branch directly?

**Comment by X-com** [comment]
I can do a merge to a experimental branch and test it out. I sadly have little time as of right now but will try get around to merging and giving it some short tests. After exams will have more time to spend on all the other planned stuff. Top of it would be this one.

**Comment by zhuyifei1999** [comment]
Alright. Thanks

**Comment by zhuyifei1999** [comment]
> The only discomfort for me is that the player movement speed is affected by world tick rate instead of player, which I guess is probably way too complicated to fix. 

I just realized, this was part of the original feature set, so I guess I do need to fix this then.

**Comment by zhuyifei1999** [comment]
> I just realized, this was part of the original feature set, so I guess I do need to fix this then.

Done, as far as I have tested.

**Comment by zhuyifei1999** [comment]
the renderHand view bobbing glitchiness may have to do with OptiFine, I observe less of a difference without OptiFine. I might be wrong though, it is somewhat subtle even with OptiFine.

Edit: Fixed in d8717e8

**Comment by zhuyifei1999** [comment]
Rendering is glitchy if player is riding something. Eg at 2tps, riding a minecraft, the minecraft the player is riding will move with 2tps speed, but the player is like teleporting every half second. Should this be fixed?

Edit: I don't see how to fix this without making the group of entities ridden by / riding on / with the player be updated at the exact same rate. If the minecart updates the player every 1/2 second, there is no way the player would not 'think' it is teleporting every 10 ticks. I suggest to update the player at world rate if the player is riding.

**Comment by X-com** [comment]
I took a break from studies to thoroughly put this to the test and non of the old rendering glitches showed up. This is amazing! I don't know what the bug was but it seams to be gone now. I will try test it on few other instances and servers but so far looks great.

**Comment by zhuyifei1999** [comment]
Probably had something similar to https://github.com/X-com/CarpetClient/pull/7/commits/3a64334cb6def64bd56baffeb43ae1dac46d0203#diff-58b529f594c7d43845ca0270054c1450R46. However, it would be instead of the player being rendered wrongly, it would be every other moving entity being rendered wrongly.

**Comment by zhuyifei1999** [comment]
And I have no idea why running with Forge failed so bad. Forge does add hooks into `runTick` method, and trying not to break Forge's hook was the primary reason I went with Class Transformer.

**Comment by X-com** [comment]
I honestly dont care about forge anymore given no mods ever need forge. Every mod that ever was used by carpet client now have been fully ported to liteloader.

**Comment by Nessiesson** [comment]
Could this not have been done with Mixin directly instead of direct ASM?

**Comment by zhuyifei1999** [comment]
The complexity that made me use ASM is that the runTick method must be
separated into two parts, those that do world ticks and those that do
player ticks. To do this with Mixin we could either do:
* Find a way with Mixin to add if statements. The best way I can think of
to do this is by hooking a ton of `@Redirect` or `@Inject` at HEAD with cancel
on every single call we want to capture. Since that is a lot of calls
spread among a few classes, the code duplication would likely go bad. Also, `@Redirect`s might conflict...
* Or `@Redirect` runTick to our own, bypassing vanilla. Unfortunately,
runTick is an obvious candidate for other mods to hook onto with Mixins.
Both Forge and Liteloader uses this for events, so if we do this, any mod
that uses such events or otherwise hooks onto runTick will silently fail. I
am not certain why the original implementation behaved differently with and
without Forge, but my guess is on this.

**Pull request merged**
